BIN = test.exe
CC = gcc
FLAGS = -Wall -pedantic -fmessage-length=78 -std=c99
INC = -I ../common/include
L = ../common/win32/
LOC_LIB = $(L)libglew32.dll.a $(L)glfw3dll.a -L./ -lSDL2
SYS_LIB = -lopengl32
SRC = main.c

all: main.c
	${CC} ${FLAGS} ${FRAMEWORKS} -o ${BIN} ${SRC} -g ${INC} ${LOC_LIB} ${SYS_LIB}
